// Code generated by scripts/generate_contracts.py. DO NOT EDIT.
package contracts

type AdminApplyRequest struct {
	SchemaVersion    int64  `json:"schema_version"`
	ChangeHash       string `json:"change_hash"`
	ExpectedRevision int64  `json:"expected_revision"`
}

type AdminChangeSet struct {
	SchemaVersion int64                  `json:"schema_version"`
	Id            string                 `json:"id"`
	FarmId        string                 `json:"farm_id"`
	PrincipalId   string                 `json:"principal_id"`
	RunId         string                 `json:"run_id"`
	Intent        AdminIntent            `json:"intent"`
	ChangeHash    string                 `json:"change_hash"`
	NodePlans     []NodePlan             `json:"node_plans"`
	Preconditions []RevisionPrecondition `json:"preconditions"`
	DownloadBytes int64                  `json:"download_bytes"`
	Disruption    string                 `json:"disruption"`
	ExpiresAt     string                 `json:"expires_at"`
}

type AdminExecutionGrant struct {
	SchemaVersion        int64    `json:"schema_version"`
	Id                   string   `json:"id"`
	FarmId               string   `json:"farm_id"`
	PrincipalId          string   `json:"principal_id"`
	RunId                string   `json:"run_id"`
	ChangeHash           *string  `json:"change_hash"`
	TargetNodeIds        []string `json:"target_node_ids"`
	Actions              []string `json:"actions"`
	MaximumDownloadBytes int64    `json:"maximum_download_bytes"`
	AuthorizationVersion int64    `json:"authorization_version"`
	ExpiresAt            string   `json:"expires_at"`
	RevokedAt            *string  `json:"revoked_at"`
}

type AdminIntent struct {
	SchemaVersion    int64          `json:"schema_version"`
	Action           string         `json:"action"`
	TargetNodeIds    []string       `json:"target_node_ids"`
	CapabilityId     *string        `json:"capability_id"`
	ApprovedRecipeId *string        `json:"approved_recipe_id"`
	Settings         map[string]any `json:"settings"`
}

type AdminOperation struct {
	SchemaVersion       int64    `json:"schema_version"`
	Id                  string   `json:"id"`
	ChangeId            string   `json:"change_id"`
	State               string   `json:"state"`
	Revision            int64    `json:"revision"`
	CompletedServiceIds []string `json:"completed_service_ids"`
	Reason              *string  `json:"reason"`
	Deadline            string   `json:"deadline"`
}

type ArtifactMetadata struct {
	SchemaVersion     int64    `json:"schema_version"`
	Id                string   `json:"id"`
	FarmId            string   `json:"farm_id"`
	OwnerId           string   `json:"owner_id"`
	WorkspaceId       string   `json:"workspace_id"`
	SourceTaskId      string   `json:"source_task_id"`
	Digest            string   `json:"digest"`
	ContentType       string   `json:"content_type"`
	SizeBytes         int64    `json:"size_bytes"`
	Locality          Locality `json:"locality"`
	SourceArtifactIds []string `json:"source_artifact_ids"`
}

type CapabilityAvailability struct {
	SchemaVersion         int64    `json:"schema_version"`
	CapabilityId          string   `json:"capability_id"`
	AssignmentState       string   `json:"assignment_state"`
	LocalState            string   `json:"local_state"`
	LocalDeploymentIds    []string `json:"local_deployment_ids"`
	ExternalTargetIds     []string `json:"external_target_ids"`
	CloudConfigured       bool     `json:"cloud_configured"`
	CloudAllowedForCaller bool     `json:"cloud_allowed_for_caller"`
	EffectiveState        string   `json:"effective_state"`
	Reason                *string  `json:"reason"`
	AvailableActions      []string `json:"available_actions"`
}

type CapabilityBinding struct {
	SchemaVersion int64  `json:"schema_version"`
	CapabilityId  string `json:"capability_id"`
	TargetId      string `json:"target_id"`
	Priority      int64  `json:"priority"`
}

type CapabilityDefinition struct {
	SchemaVersion           int64    `json:"schema_version"`
	CapabilityId            string   `json:"capability_id"`
	Revision                int64    `json:"revision"`
	DisplayName             string   `json:"display_name"`
	Description             string   `json:"description"`
	Icon                    string   `json:"icon"`
	InputModalities         []string `json:"input_modalities"`
	OutputModalities        []string `json:"output_modalities"`
	RequiredFeatures        []string `json:"required_features"`
	PermittedToolCategories []string `json:"permitted_tool_categories"`
	QualitySuite            string   `json:"quality_suite"`
	DeadlineSeconds         int64    `json:"deadline_seconds"`
	CloudEligible           bool     `json:"cloud_eligible"`
	Enabled                 bool     `json:"enabled"`
}

type CloudAuthorization struct {
	SchemaVersion             int64      `json:"schema_version"`
	ProviderEnabled           bool       `json:"provider_enabled"`
	CapabilityAllowed         bool       `json:"capability_allowed"`
	UserOptIn                 bool       `json:"user_opt_in"`
	WorkspaceAllowed          bool       `json:"workspace_allowed"`
	PriceKnown                bool       `json:"price_known"`
	FarmRemainingMinor        int64      `json:"farm_remaining_minor"`
	UserRemainingMinor        int64      `json:"user_remaining_minor"`
	RequestedReservationMinor int64      `json:"requested_reservation_minor"`
	InputLocalities           []Locality `json:"input_localities"`
}

type ConversationImage struct {
	SchemaVersion int64           `json:"schema_version"`
	Request       ImageGeneration `json:"request"`
	Status        string          `json:"status"`
	Progress      int64           `json:"progress"`
	Reason        *string         `json:"reason"`
	Sha256        *string         `json:"sha256"`
	PlanningModel *string         `json:"planning_model"`
	SourceImageId *string         `json:"source_image_id"`
	Variation     bool            `json:"variation"`
	BatchIndex    int64           `json:"batch_index"`
	BatchCount    int64           `json:"batch_count"`
}

type EnrollmentEnvelope struct {
	SchemaVersion        int64  `json:"schema_version"`
	FarmId               string `json:"farm_id"`
	NodeId               string `json:"node_id"`
	AttemptId            string `json:"attempt_id"`
	Nonce                string `json:"nonce"`
	PublicKeyFingerprint string `json:"public_key_fingerprint"`
	FarmCaPem            string `json:"farm_ca_pem"`
	ControlOrigin        string `json:"control_origin"`
	EnrollmentToken      string `json:"enrollment_token"`
	ExpiresAt            string `json:"expires_at"`
}

type EnrollmentPending struct {
	SchemaVersion        int64  `json:"schema_version"`
	AttemptId            string `json:"attempt_id"`
	NodeId               string `json:"node_id"`
	Nonce                string `json:"nonce"`
	PublicKeyFingerprint string `json:"public_key_fingerprint"`
	DisplayName          string `json:"display_name"`
	ProtocolVersion      int64  `json:"protocol_version"`
}

type ErrorDetail struct {
	SchemaVersion int64  `json:"schema_version"`
	Code          string `json:"code"`
	Message       string `json:"message"`
	Retryable     bool   `json:"retryable"`
	TraceId       string `json:"trace_id"`
}

type ErrorResponse struct {
	SchemaVersion int64       `json:"schema_version"`
	Error         ErrorDetail `json:"error"`
}

type EventEnvelope struct {
	SchemaVersion    int64          `json:"schema_version"`
	EventId          string         `json:"event_id"`
	EventType        string         `json:"event_type"`
	OccurredAt       string         `json:"occurred_at"`
	AggregateId      string         `json:"aggregate_id"`
	AggregateVersion int64          `json:"aggregate_version"`
	TraceId          string         `json:"trace_id"`
	Data             map[string]any `json:"data"`
}

type ExternalProviderConnection struct {
	SchemaVersion        int64  `json:"schema_version"`
	Id                   string `json:"id"`
	FarmId               string `json:"farm_id"`
	Name                 string `json:"name"`
	BaseUrl              string `json:"base_url"`
	Protocol             string `json:"protocol"`
	Management           string `json:"management"`
	LocalityAssurance    string `json:"locality_assurance"`
	CredentialConfigured bool   `json:"credential_configured"`
}

type GeometryGeneration struct {
	SchemaVersion int64  `json:"schema_version"`
	Id            string `json:"id"`
	Model         string `json:"model"`
	ImageSha256   string `json:"image_sha256"`
	Seed          int64  `json:"seed"`
	Resolution    int64  `json:"resolution"`
}

type GeometryProviderInfo struct {
	SchemaVersion   int64   `json:"schema_version"`
	Protocol        string  `json:"protocol"`
	Model           string  `json:"model"`
	ModelRevision   string  `json:"model_revision"`
	ManifestSha256  string  `json:"manifest_sha256"`
	Offline         bool    `json:"offline"`
	JobCancellation bool    `json:"job_cancellation"`
	Resolutions     []int64 `json:"resolutions"`
	OutputFormat    string  `json:"output_format"`
}

type GeometryReceipt struct {
	SchemaVersion     int64   `json:"schema_version"`
	Id                string  `json:"id"`
	Model             string  `json:"model"`
	ImageSha256       string  `json:"image_sha256"`
	Seed              int64   `json:"seed"`
	Resolution        int64   `json:"resolution"`
	State             string  `json:"state"`
	Progress          int64   `json:"progress"`
	Reason            *string `json:"reason"`
	Sha256            *string `json:"sha256"`
	ExecutionReleased bool    `json:"execution_released"`
	ManifestSha256    string  `json:"manifest_sha256"`
	CancelRequested   bool    `json:"cancel_requested"`
}

type GeometryRequest struct {
	SchemaVersion      int64   `json:"schema_version"`
	Prompt             *string `json:"prompt"`
	InputImageId       *string `json:"input_image_id"`
	OutputFormat       string  `json:"output_format"`
	Units              string  `json:"units"`
	UpAxis             string  `json:"up_axis"`
	MaximumTriangles   int64   `json:"maximum_triangles"`
	MaximumTextureSize int64   `json:"maximum_texture_size"`
}

type Heartbeat struct {
	SchemaVersion        int64                `json:"schema_version"`
	NodeId               string               `json:"node_id"`
	FarmId               string               `json:"farm_id"`
	NodeEpoch            int64                `json:"node_epoch"`
	ControllerGeneration int64                `json:"controller_generation"`
	Sequence             int64                `json:"sequence"`
	ObservedPlanRevision int64                `json:"observed_plan_revision"`
	ActiveAttemptIds     []string             `json:"active_attempt_ids"`
	Services             []ServiceObservation `json:"services"`
}

type ImageGeneration struct {
	SchemaVersion  int64        `json:"schema_version"`
	Id             string       `json:"id"`
	Model          string       `json:"model"`
	Prompt         string       `json:"prompt"`
	NegativePrompt string       `json:"negative_prompt"`
	Shape          string       `json:"shape"`
	Steps          int64        `json:"steps"`
	Seed           int64        `json:"seed"`
	Options        ImageOptions `json:"options"`
}

type ImageOptions struct {
	SchemaVersion int64     `json:"schema_version"`
	Resolution    string    `json:"resolution"`
	Styles        *[]string `json:"styles"`
	GuidanceScale *float64  `json:"guidance_scale"`
	Sharpness     *float64  `json:"sharpness"`
}

type ImageOptionsProfile struct {
	SchemaVersion int64    `json:"schema_version"`
	Resolutions   []string `json:"resolutions"`
	Styles        []string `json:"styles"`
	DefaultStyles []string `json:"default_styles"`
	GuidanceScale *float64 `json:"guidance_scale"`
	Sharpness     *float64 `json:"sharpness"`
}

type ImagePrompt struct {
	SchemaVersion  int64  `json:"schema_version"`
	Prompt         string `json:"prompt"`
	NegativePrompt string `json:"negative_prompt"`
	Shape          string `json:"shape"`
}

type ImagePromptPlan struct {
	SchemaVersion  int64          `json:"schema_version"`
	Action         string         `json:"action"`
	Prompt         *string        `json:"prompt"`
	NegativePrompt string         `json:"negative_prompt"`
	Shape          string         `json:"shape"`
	Question       *string        `json:"question"`
	Images         *[]ImagePrompt `json:"images"`
}

type ImageProviderInfo struct {
	SchemaVersion   int64                `json:"schema_version"`
	Protocol        string               `json:"protocol"`
	Model           string               `json:"model"`
	ModelRevision   string               `json:"model_revision"`
	ManifestSha256  string               `json:"manifest_sha256"`
	Shapes          []string             `json:"shapes"`
	Steps           []int64              `json:"steps"`
	Options         *ImageOptionsProfile `json:"options"`
	JobCancellation bool                 `json:"job_cancellation"`
	Offline         bool                 `json:"offline"`
}

type ImageReceipt struct {
	SchemaVersion     int64   `json:"schema_version"`
	Id                string  `json:"id"`
	Model             string  `json:"model"`
	State             string  `json:"state"`
	Progress          int64   `json:"progress"`
	Steps             int64   `json:"steps"`
	Seed              int64   `json:"seed"`
	Shape             string  `json:"shape"`
	Width             int64   `json:"width"`
	Height            int64   `json:"height"`
	Reason            *string `json:"reason"`
	Sha256            *string `json:"sha256"`
	ExecutionReleased bool    `json:"execution_released"`
	ManifestSha256    string  `json:"manifest_sha256"`
	CancelRequested   bool    `json:"cancel_requested"`
}

type InferenceTarget struct {
	SchemaVersion  int64    `json:"schema_version"`
	Id             string   `json:"id"`
	ConnectionId   string   `json:"connection_id"`
	ResourcePoolId string   `json:"resource_pool_id"`
	ModelId        string   `json:"model_id"`
	State          string   `json:"state"`
	Features       []string `json:"features"`
	ProbedAt       *string  `json:"probed_at"`
	VerifiedUntil  *string  `json:"verified_until"`
	Revision       int64    `json:"revision"`
}

type JobScope struct {
	SchemaVersion        int64    `json:"schema_version"`
	FarmId               string   `json:"farm_id"`
	PrincipalId          string   `json:"principal_id"`
	WorkspaceId          string   `json:"workspace_id"`
	TaskId               string   `json:"task_id"`
	ParentTaskId         *string  `json:"parent_task_id"`
	AuthorizationVersion int64    `json:"authorization_version"`
	ResourceGrantIds     []string `json:"resource_grant_ids"`
	Locality             Locality `json:"locality"`
	RemainingBudgetId    string   `json:"remaining_budget_id"`
	Audience             string   `json:"audience"`
	AttemptId            string   `json:"attempt_id"`
	FencingToken         int64    `json:"fencing_token"`
	ExpiresAt            string   `json:"expires_at"`
}

type Locality string
type NodePlan struct {
	SchemaVersion        int64         `json:"schema_version"`
	FarmId               string        `json:"farm_id"`
	NodeId               string        `json:"node_id"`
	ControllerGeneration int64         `json:"controller_generation"`
	NodeEpoch            int64         `json:"node_epoch"`
	ExpectedRevision     int64         `json:"expected_revision"`
	DesiredRevision      int64         `json:"desired_revision"`
	Services             []ServicePlan `json:"services"`
	DrainPolicy          string        `json:"drain_policy"`
	ExpiresAt            string        `json:"expires_at"`
}

type PackageReference struct {
	SchemaVersion int64  `json:"schema_version"`
	PackageId     string `json:"package_id"`
	Digest        string `json:"digest"`
	SizeBytes     int64  `json:"size_bytes"`
	SignerId      string `json:"signer_id"`
}

type ProviderBootstrap struct {
	SchemaVersion           int64   `json:"schema_version"`
	Id                      string  `json:"id"`
	Path                    string  `json:"path"`
	Readiness               string  `json:"readiness"`
	NodeId                  *string `json:"node_id"`
	DeploymentId            *string `json:"deployment_id"`
	ProviderConfigurationId *string `json:"provider_configuration_id"`
	ProbeEvidenceId         *string `json:"probe_evidence_id"`
	Reason                  *string `json:"reason"`
	Revision                int64   `json:"revision"`
}

type ProviderProbeRequest struct {
	SchemaVersion    int64   `json:"schema_version"`
	ExpectedRevision int64   `json:"expected_revision"`
	MaximumCostMinor int64   `json:"maximum_cost_minor"`
	PaidProbeGrantId *string `json:"paid_probe_grant_id"`
}

type ProviderResourcePool struct {
	SchemaVersion   int64  `json:"schema_version"`
	Id              string `json:"id"`
	Name            string `json:"name"`
	GenerationSlots int64  `json:"generation_slots"`
	Busy            bool   `json:"busy"`
	ExecutionState  string `json:"execution_state"`
}

type RecipeDependency struct {
	SchemaVersion int64            `json:"schema_version"`
	DependencyId  string           `json:"dependency_id"`
	Package       PackageReference `json:"package"`
	DependsOn     []string         `json:"depends_on"`
}

type ResourceEnvelope struct {
	SchemaVersion   int64 `json:"schema_version"`
	RamBytes        int64 `json:"ram_bytes"`
	VramBytes       int64 `json:"vram_bytes"`
	DiskBytes       int64 `json:"disk_bytes"`
	CpuMillicores   int64 `json:"cpu_millicores"`
	GenerationSlots int64 `json:"generation_slots"`
}

type RevisionPrecondition struct {
	SchemaVersion    int64  `json:"schema_version"`
	ResourceId       string `json:"resource_id"`
	ExpectedRevision int64  `json:"expected_revision"`
}

type SecureInputReceipt struct {
	SchemaVersion int64  `json:"schema_version"`
	ReceiptId     string `json:"receipt_id"`
	RunId         string `json:"run_id"`
	ResourceId    string `json:"resource_id"`
	Form          string `json:"form"`
	Status        string `json:"status"`
	ExpiresAt     string `json:"expires_at"`
}

type ServiceObservation struct {
	SchemaVersion     int64   `json:"schema_version"`
	ServiceInstanceId string  `json:"service_instance_id"`
	DesiredRevision   int64   `json:"desired_revision"`
	ObservedRevision  int64   `json:"observed_revision"`
	State             string  `json:"state"`
	Reason            *string `json:"reason"`
	CompletedBytes    int64   `json:"completed_bytes"`
	TotalBytes        *int64  `json:"total_bytes"`
	ObservedAt        string  `json:"observed_at"`
}

type ServicePlan struct {
	SchemaVersion      int64            `json:"schema_version"`
	ServiceInstanceId  string           `json:"service_instance_id"`
	RecipeId           string           `json:"recipe_id"`
	RecipeDigest       string           `json:"recipe_digest"`
	PackageDigests     []string         `json:"package_digests"`
	ModelDigests       []string         `json:"model_digests"`
	CapabilityIds      []string         `json:"capability_ids"`
	Settings           map[string]any   `json:"settings"`
	SecretReferenceIds []string         `json:"secret_reference_ids"`
	Reservations       ResourceEnvelope `json:"reservations"`
	Pinned             bool             `json:"pinned"`
}

type ServiceRecipe struct {
	SchemaVersion       int64              `json:"schema_version"`
	RecipeId            string             `json:"recipe_id"`
	Revision            int64              `json:"revision"`
	Digest              string             `json:"digest"`
	Platforms           []string           `json:"platforms"`
	Capabilities        []string           `json:"capabilities"`
	Dependencies        []RecipeDependency `json:"dependencies"`
	EntrypointId        string             `json:"entrypoint_id"`
	MinimumNodeProtocol int64              `json:"minimum_node_protocol"`
	Isolation           string             `json:"isolation"`
	SettingsSchema      map[string]any     `json:"settings_schema"`
	ReadinessProbe      string             `json:"readiness_probe"`
	Rollback            string             `json:"rollback"`
}

type SpeechGeneration struct {
	SchemaVersion int64  `json:"schema_version"`
	Id            string `json:"id"`
	Model         string `json:"model"`
	Voice         string `json:"voice"`
	Input         string `json:"input"`
}

type SpeechProviderInfo struct {
	SchemaVersion     int64    `json:"schema_version"`
	Protocol          string   `json:"protocol"`
	Model             string   `json:"model"`
	ModelRevision     string   `json:"model_revision"`
	ManifestSha256    string   `json:"manifest_sha256"`
	Voices            []string `json:"voices"`
	DefaultVoice      string   `json:"default_voice"`
	MaximumCharacters int64    `json:"maximum_characters"`
	SampleRate        int64    `json:"sample_rate"`
	JobCancellation   bool     `json:"job_cancellation"`
	Offline           bool     `json:"offline"`
}

type SpeechReceipt struct {
	SchemaVersion     int64   `json:"schema_version"`
	Id                string  `json:"id"`
	Model             string  `json:"model"`
	Voice             string  `json:"voice"`
	InputSha256       string  `json:"input_sha256"`
	State             string  `json:"state"`
	Reason            *string `json:"reason"`
	Sha256            *string `json:"sha256"`
	Frames            int64   `json:"frames"`
	SampleRate        int64   `json:"sample_rate"`
	ExecutionReleased bool    `json:"execution_released"`
	ManifestSha256    string  `json:"manifest_sha256"`
	CancelRequested   bool    `json:"cancel_requested"`
}

type TranscriptionProviderInfo struct {
	SchemaVersion   int64    `json:"schema_version"`
	Protocol        string   `json:"protocol"`
	Model           string   `json:"model"`
	ModelRevision   string   `json:"model_revision"`
	ManifestSha256  string   `json:"manifest_sha256"`
	Languages       []string `json:"languages"`
	MaximumSeconds  int64    `json:"maximum_seconds"`
	SampleRate      int64    `json:"sample_rate"`
	JobCancellation bool     `json:"job_cancellation"`
	Offline         bool     `json:"offline"`
}

type TranscriptionReceipt struct {
	SchemaVersion     int64   `json:"schema_version"`
	Id                string  `json:"id"`
	Model             string  `json:"model"`
	AudioSha256       string  `json:"audio_sha256"`
	State             string  `json:"state"`
	Reason            *string `json:"reason"`
	Text              string  `json:"text"`
	Language          string  `json:"language"`
	ExecutionReleased bool    `json:"execution_released"`
	ManifestSha256    string  `json:"manifest_sha256"`
	CancelRequested   bool    `json:"cancel_requested"`
}

type TranscriptionRequest struct {
	SchemaVersion int64  `json:"schema_version"`
	Id            string `json:"id"`
	Model         string `json:"model"`
	AudioSha256   string `json:"audio_sha256"`
}

type WorkerCommand struct {
	SchemaVersion   int64  `json:"schema_version"`
	CommandId       string `json:"command_id"`
	NodeId          string `json:"node_id"`
	NodeEpoch       int64  `json:"node_epoch"`
	Operation       string `json:"operation"`
	ReferenceId     string `json:"reference_id"`
	ReferenceDigest string `json:"reference_digest"`
	ExpiresAt       string `json:"expires_at"`
}
