/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Draft */
        post: operations["create_draft_api_v1_drafts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Draft */
        get: operations["draft_api_v1_drafts__draft_id__get"];
        /** Update Draft */
        put: operations["update_draft_api_v1_drafts__draft_id__put"];
        post?: never;
        /** Archive Draft */
        delete: operations["archive_draft_api_v1_drafts__draft_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/farm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Farm */
        get: operations["farm_api_v1_farm_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session_api_v1_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Setup */
        get: operations["setup_api_v1_setup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace */
        get: operations["workspace_api_v1_workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminApplyRequest */
        AdminApplyRequest: {
            /** Change Hash */
            change_hash: string;
            /** Expected Revision */
            expected_revision: number;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** AdminChangeSet */
        AdminChangeSet: {
            /** Change Hash */
            change_hash: string;
            /** Disruption */
            disruption: string;
            /** Download Bytes */
            download_bytes: number;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Farm Id
             * Format: uuid
             */
            farm_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            intent: components["schemas"]["AdminIntent"];
            /** Node Plans */
            node_plans?: components["schemas"]["NodePlan"][];
            /** Preconditions */
            preconditions: components["schemas"]["RevisionPrecondition"][];
            /**
             * Principal Id
             * Format: uuid
             */
            principal_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * AdminExecutionGrant
         * @description Server-held record, never a model tool argument or public response.
         */
        AdminExecutionGrant: {
            /** Actions */
            actions: string[];
            /** Authorization Version */
            authorization_version: number;
            /**
             * Change Hash
             * @default null
             */
            change_hash: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Farm Id
             * Format: uuid
             */
            farm_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Maximum Download Bytes */
            maximum_download_bytes: number;
            /**
             * Principal Id
             * Format: uuid
             */
            principal_id: string;
            /**
             * Revoked At
             * @default null
             */
            revoked_at: string | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Target Node Ids */
            target_node_ids: string[];
        };
        /** AdminIntent */
        AdminIntent: {
            /**
             * Action
             * @enum {string}
             */
            action: "assign_capability" | "configure_service" | "drain_node" | "resume_node" | "retry_service";
            /**
             * Approved Recipe Id
             * @default null
             */
            approved_recipe_id: string | null;
            /**
             * Capability Id
             * @default null
             */
            capability_id: string | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Settings */
            settings?: {
                [key: string]: unknown;
            };
            /** Target Node Ids */
            target_node_ids: string[];
        };
        /** AdminOperation */
        AdminOperation: {
            /**
             * Change Id
             * Format: uuid
             */
            change_id: string;
            /** Completed Service Ids */
            completed_service_ids?: string[];
            /**
             * Deadline
             * Format: date-time
             */
            deadline: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Reason
             * @default null
             */
            reason: string | null;
            /** Revision */
            revision: number;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * State
             * @enum {string}
             */
            state: "accepted" | "running" | "waiting_node" | "completed" | "partially_completed" | "failed" | "cancelled";
        };
        /** ArtifactMetadata */
        ArtifactMetadata: {
            /** Content Type */
            content_type: string;
            /** Digest */
            digest: string;
            /**
             * Farm Id
             * Format: uuid
             */
            farm_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** @default local_only */
            locality: components["schemas"]["Locality"];
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Size Bytes */
            size_bytes: number;
            /** Source Artifact Ids */
            source_artifact_ids?: string[];
            /**
             * Source Task Id
             * Format: uuid
             */
            source_task_id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** CapabilityAvailability */
        CapabilityAvailability: {
            /**
             * Assignment State
             * @enum {string}
             */
            assignment_state: "unassigned" | "assigned" | "disabled";
            /** Available Actions */
            available_actions?: string[];
            /** Capability Id */
            capability_id: string;
            /**
             * Cloud Allowed For Caller
             * @default false
             */
            cloud_allowed_for_caller: boolean;
            /**
             * Cloud Configured
             * @default false
             */
            cloud_configured: boolean;
            /**
             * Effective State
             * @enum {string}
             */
            effective_state: "unavailable" | "warming" | "ready" | "busy" | "cloud_available";
            /** Local Deployment Ids */
            local_deployment_ids?: string[];
            /**
             * Local State
             * @enum {string}
             */
            local_state: "unavailable" | "warming" | "ready" | "busy" | "offline" | "failed";
            /**
             * Reason
             * @default null
             */
            reason: string | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** CapabilityDefinition */
        CapabilityDefinition: {
            /** Capability Id */
            capability_id: string;
            /**
             * Cloud Eligible
             * @default false
             */
            cloud_eligible: boolean;
            /**
             * Deadline Seconds
             * @default 300
             */
            deadline_seconds: number;
            /** Description */
            description: string;
            /** Display Name */
            display_name: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Icon */
            icon: string;
            /** Input Modalities */
            input_modalities: ("text" | "image" | "audio" | "artifact")[];
            /** Output Modalities */
            output_modalities: ("text" | "image" | "audio" | "geometry" | "artifact")[];
            /** Permitted Tool Categories */
            permitted_tool_categories?: string[];
            /** Quality Suite */
            quality_suite: string;
            /** Required Features */
            required_features?: string[];
            /** Revision */
            revision: number;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** CloudAuthorization */
        CloudAuthorization: {
            /** Capability Allowed */
            capability_allowed: boolean;
            /** Farm Remaining Minor */
            farm_remaining_minor: number;
            /** Input Localities */
            input_localities: components["schemas"]["Locality"][];
            /** Price Known */
            price_known: boolean;
            /** Provider Enabled */
            provider_enabled: boolean;
            /** Requested Reservation Minor */
            requested_reservation_minor: number;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** User Opt In */
            user_opt_in: boolean;
            /** User Remaining Minor */
            user_remaining_minor: number;
            /** Workspace Allowed */
            workspace_allowed: boolean;
        };
        /** DraftInput */
        DraftInput: {
            /** Content */
            content: string;
            /** Title */
            title: string;
        };
        /** DraftUpdate */
        DraftUpdate: {
            /** Content */
            content: string;
            /** Revision */
            revision: number;
            /** Title */
            title: string;
        };
        /** EnrollmentEnvelope */
        EnrollmentEnvelope: {
            /**
             * Attempt Id
             * Format: uuid
             */
            attempt_id: string;
            /** Control Origin */
            control_origin: string;
            /** Enrollment Token */
            enrollment_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Farm Ca Pem */
            farm_ca_pem: string;
            /**
             * Farm Id
             * Format: uuid
             */
            farm_id: string;
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /** Nonce */
            nonce: string;
            /** Public Key Fingerprint */
            public_key_fingerprint: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** EnrollmentPending */
        EnrollmentPending: {
            /**
             * Attempt Id
             * Format: uuid
             */
            attempt_id: string;
            /** Display Name */
            display_name: string;
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /** Nonce */
            nonce: string;
            /**
             * Protocol Version
             * @default 1
             * @constant
             */
            protocol_version: 1;
            /** Public Key Fingerprint */
            public_key_fingerprint: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** EventEnvelope */
        EventEnvelope: {
            /**
             * Aggregate Id
             * Format: uuid
             */
            aggregate_id: string;
            /** Aggregate Version */
            aggregate_version: number;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Event Type */
            event_type: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
        };
        /** GeometryRequest */
        GeometryRequest: {
            /**
             * Input Image Id
             * @default null
             */
            input_image_id: string | null;
            /**
             * Maximum Texture Size
             * @default 2048
             * @enum {integer}
             */
            maximum_texture_size: 512 | 1024 | 2048 | 4096;
            /**
             * Maximum Triangles
             * @default 100000
             */
            maximum_triangles: number;
            /**
             * Output Format
             * @default glb
             * @constant
             */
            output_format: "glb";
            /**
             * Prompt
             * @default null
             */
            prompt: string | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Units
             * @default meters
             * @constant
             */
            units: "meters";
            /**
             * Up Axis
             * @default Y
             * @constant
             */
            up_axis: "Y";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Heartbeat */
        Heartbeat: {
            /** Active Attempt Ids */
            active_attempt_ids?: string[];
            /** Controller Generation */
            controller_generation: number;
            /**
             * Farm Id
             * Format: uuid
             */
            farm_id: string;
            /** Node Epoch */
            node_epoch: number;
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /** Observed Plan Revision */
            observed_plan_revision: number;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Sequence */
            sequence: number;
            /** Services */
            services?: components["schemas"]["ServiceObservation"][];
        };
        /** JobScope */
        JobScope: {
            /**
             * Attempt Id
             * Format: uuid
             */
            attempt_id: string;
            /** Audience */
            audience: string;
            /** Authorization Version */
            authorization_version: number;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Farm Id
             * Format: uuid
             */
            farm_id: string;
            /** Fencing Token */
            fencing_token: number;
            /** @default local_only */
            locality: components["schemas"]["Locality"];
            /**
             * Parent Task Id
             * @default null
             */
            parent_task_id: string | null;
            /**
             * Principal Id
             * Format: uuid
             */
            principal_id: string;
            /**
             * Remaining Budget Id
             * Format: uuid
             */
            remaining_budget_id: string;
            /** Resource Grant Ids */
            resource_grant_ids?: string[];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /**
         * Locality
         * @enum {string}
         */
        Locality: "local_only" | "cloud_allowed";
        /** NodePlan */
        NodePlan: {
            /** Controller Generation */
            controller_generation: number;
            /** Desired Revision */
            desired_revision: number;
            /**
             * Drain Policy
             * @default finish_active
             * @enum {string}
             */
            drain_policy: "finish_active" | "cancel_active";
            /** Expected Revision */
            expected_revision: number;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Farm Id
             * Format: uuid
             */
            farm_id: string;
            /** Node Epoch */
            node_epoch: number;
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Services */
            services?: components["schemas"]["ServicePlan"][];
        };
        /** PackageReference */
        PackageReference: {
            /** Digest */
            digest: string;
            /** Package Id */
            package_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Signer Id */
            signer_id: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** ProviderBootstrap */
        ProviderBootstrap: {
            /**
             * Deployment Id
             * @default null
             */
            deployment_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Node Id
             * @default null
             */
            node_id: string | null;
            /**
             * Path
             * @enum {string}
             */
            path: "local_head" | "joined_member" | "openai";
            /**
             * Probe Evidence Id
             * @default null
             */
            probe_evidence_id: string | null;
            /**
             * Provider Configuration Id
             * @default null
             */
            provider_configuration_id: string | null;
            /**
             * Readiness
             * @enum {string}
             */
            readiness: "unconfigured" | "configured" | "inference_verified" | "admin_agent_ready" | "failed";
            /**
             * Reason
             * @default null
             */
            reason: string | null;
            /** Revision */
            revision: number;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** ProviderProbeRequest */
        ProviderProbeRequest: {
            /** Expected Revision */
            expected_revision: number;
            /**
             * Maximum Cost Minor
             * @default 0
             */
            maximum_cost_minor: number;
            /**
             * Paid Probe Grant Id
             * @default null
             */
            paid_probe_grant_id: string | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** RecipeDependency */
        RecipeDependency: {
            /** Dependency Id */
            dependency_id: string;
            /** Depends On */
            depends_on?: string[];
            package: components["schemas"]["PackageReference"];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** ResourceEnvelope */
        ResourceEnvelope: {
            /** Cpu Millicores */
            cpu_millicores: number;
            /** Disk Bytes */
            disk_bytes: number;
            /**
             * Generation Slots
             * @default 0
             */
            generation_slots: number;
            /** Ram Bytes */
            ram_bytes: number;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Vram Bytes */
            vram_bytes: number;
        };
        /** RevisionPrecondition */
        RevisionPrecondition: {
            /** Expected Revision */
            expected_revision: number;
            /**
             * Resource Id
             * Format: uuid
             */
            resource_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** SecureInputReceipt */
        SecureInputReceipt: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Form
             * @enum {string}
             */
            form: "provider_credential" | "nas_connector" | "pairing" | "model_license";
            /**
             * Receipt Id
             * Format: uuid
             */
            receipt_id: string;
            /**
             * Resource Id
             * Format: uuid
             */
            resource_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Status
             * @enum {string}
             */
            status: "awaiting_input" | "validated" | "failed" | "expired";
        };
        /** ServiceObservation */
        ServiceObservation: {
            /**
             * Completed Bytes
             * @default 0
             */
            completed_bytes: number;
            /** Desired Revision */
            desired_revision: number;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Observed Revision */
            observed_revision: number;
            /**
             * Reason
             * @default null
             */
            reason: string | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Service Instance Id
             * Format: uuid
             */
            service_instance_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "unassigned" | "planning" | "downloading" | "installing" | "configuring" | "starting" | "warming" | "ready" | "degraded" | "draining" | "stopped" | "failed";
            /**
             * Total Bytes
             * @default null
             */
            total_bytes: number | null;
        };
        /** ServicePlan */
        ServicePlan: {
            /** Capability Ids */
            capability_ids?: string[];
            /** Model Digests */
            model_digests?: string[];
            /** Package Digests */
            package_digests: string[];
            /**
             * Pinned
             * @default true
             */
            pinned: boolean;
            /** Recipe Digest */
            recipe_digest: string;
            /** Recipe Id */
            recipe_id: string;
            reservations: components["schemas"]["ResourceEnvelope"];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Secret Reference Ids */
            secret_reference_ids?: string[];
            /**
             * Service Instance Id
             * Format: uuid
             */
            service_instance_id: string;
            /** Settings */
            settings?: {
                [key: string]: unknown;
            };
        };
        /** ServiceRecipe */
        ServiceRecipe: {
            /** Capabilities */
            capabilities?: string[];
            /** Dependencies */
            dependencies: components["schemas"]["RecipeDependency"][];
            /** Digest */
            digest: string;
            /**
             * Entrypoint Id
             * @enum {string}
             */
            entrypoint_id: "llama_cpp" | "diffusers" | "whisper_cpp" | "kokoro_onnx" | "geometry" | "toolbox" | "knowledge" | "storage_gateway";
            /**
             * Isolation
             * @enum {string}
             */
            isolation: "native_unprivileged" | "linux_container";
            /**
             * Minimum Node Protocol
             * @default 1
             * @constant
             */
            minimum_node_protocol: 1;
            /** Platforms */
            platforms: ("windows_amd64" | "linux_amd64" | "darwin_amd64" | "darwin_arm64" | "linux_arm64")[];
            /** Readiness Probe */
            readiness_probe: string;
            /** Recipe Id */
            recipe_id: string;
            /** Revision */
            revision: number;
            /**
             * Rollback
             * @enum {string}
             */
            rollback: "compatible" | "restore_required";
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Settings Schema */
            settings_schema: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkerCommand */
        WorkerCommand: {
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Node Epoch */
            node_epoch: number;
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /**
             * Operation
             * @enum {string}
             */
            operation: "reconcile_plan" | "stage" | "load" | "drain" | "unload" | "cancel_attempt";
            /** Reference Digest */
            reference_digest: string;
            /**
             * Reference Id
             * Format: uuid
             */
            reference_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_draft_api_v1_drafts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_api_v1_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_draft_api_v1_drafts__draft_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_draft_api_v1_drafts__draft_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    farm_api_v1_farm_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_api_v1_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    session_api_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    setup_api_v1_setup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    workspace_api_v1_workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
