// Generated by scripts/generate_contracts.py. Do not edit.
export interface AdminApplyRequest {
  schema_version?: 1;
  change_hash: string;
  expected_revision: number;
}

export interface AdminChangeSet {
  schema_version?: 1;
  id: string;
  farm_id: string;
  principal_id: string;
  run_id: string;
  intent: AdminIntent;
  change_hash: string;
  node_plans?: Array<NodePlan>;
  preconditions: Array<RevisionPrecondition>;
  download_bytes: number;
  disruption: string;
  expires_at: string;
}

export interface AdminExecutionGrant {
  schema_version?: 1;
  id: string;
  farm_id: string;
  principal_id: string;
  run_id: string;
  change_hash?: string | null;
  target_node_ids: Array<string>;
  actions: Array<string>;
  maximum_download_bytes: number;
  authorization_version: number;
  expires_at: string;
  revoked_at?: string | null;
}

export interface AdminIntent {
  schema_version?: 1;
  action: "assign_capability" | "configure_service" | "drain_node" | "resume_node" | "retry_service";
  target_node_ids: Array<string>;
  capability_id?: string | null;
  approved_recipe_id?: string | null;
  settings?: Record<string, unknown>;
}

export interface AdminOperation {
  schema_version?: 1;
  id: string;
  change_id: string;
  state: "accepted" | "running" | "waiting_node" | "completed" | "partially_completed" | "failed" | "cancelled";
  revision: number;
  completed_service_ids?: Array<string>;
  reason?: string | null;
  deadline: string;
}

export interface ArtifactMetadata {
  schema_version?: 1;
  id: string;
  farm_id: string;
  owner_id: string;
  workspace_id: string;
  source_task_id: string;
  digest: string;
  content_type: string;
  size_bytes: number;
  locality?: Locality;
  source_artifact_ids?: Array<string>;
}

export interface CapabilityAvailability {
  schema_version?: 2;
  capability_id: string;
  assignment_state: "unassigned" | "assigned" | "disabled";
  local_state: "unavailable" | "warming" | "ready" | "busy" | "offline" | "failed";
  local_deployment_ids?: Array<string>;
  external_target_ids?: Array<string>;
  cloud_configured?: boolean;
  cloud_allowed_for_caller?: boolean;
  effective_state: "unavailable" | "warming" | "ready" | "busy" | "cloud_available";
  reason?: string | null;
  available_actions?: Array<string>;
}

export interface CapabilityBinding {
  schema_version?: 1;
  capability_id: string;
  target_id: string;
  priority?: number;
}

export interface CapabilityDefinition {
  schema_version?: 1;
  capability_id: string;
  revision: number;
  display_name: string;
  description: string;
  icon: string;
  input_modalities: Array<"text" | "image" | "audio" | "artifact">;
  output_modalities: Array<"text" | "image" | "audio" | "geometry" | "artifact">;
  required_features?: Array<string>;
  permitted_tool_categories?: Array<string>;
  quality_suite: string;
  deadline_seconds?: number;
  cloud_eligible?: boolean;
  enabled?: boolean;
}

export interface CloudAuthorization {
  schema_version?: 1;
  provider_enabled: boolean;
  capability_allowed: boolean;
  user_opt_in: boolean;
  workspace_allowed: boolean;
  price_known: boolean;
  farm_remaining_minor: number;
  user_remaining_minor: number;
  requested_reservation_minor: number;
  input_localities: Array<Locality>;
}

export interface ConversationImage {
  schema_version?: 1;
  request: ImageGeneration;
  status: "queued" | "running" | "completed" | "cancelled" | "failed" | "interrupted" | "deleted";
  progress: number;
  reason?: string | null;
  sha256?: string | null;
  planning_model?: string | null;
  source_image_id?: string | null;
  variation?: boolean;
  batch_index?: number;
  batch_count?: number;
}

export interface EnrollmentEnvelope {
  schema_version?: 1;
  farm_id: string;
  node_id: string;
  attempt_id: string;
  nonce: string;
  public_key_fingerprint: string;
  farm_ca_pem: string;
  control_origin: string;
  enrollment_token: string;
  expires_at: string;
}

export interface EnrollmentPending {
  schema_version?: 1;
  attempt_id: string;
  node_id: string;
  nonce: string;
  public_key_fingerprint: string;
  display_name: string;
  protocol_version?: 1;
}

export interface ErrorDetail {
  schema_version?: 1;
  code: string;
  message: string;
  retryable?: boolean;
  trace_id: string;
}

export interface ErrorResponse {
  schema_version?: 1;
  error: ErrorDetail;
}

export interface EventEnvelope {
  schema_version?: 1;
  event_id: string;
  event_type: string;
  occurred_at: string;
  aggregate_id: string;
  aggregate_version: number;
  trace_id: string;
  data?: Record<string, unknown>;
}

export interface ExternalProviderConnection {
  schema_version?: 1;
  id: string;
  farm_id: string;
  name: string;
  base_url: string;
  protocol?: "openai_compatible";
  management?: "external";
  locality_assurance?: "operator_declared_local";
  credential_configured?: boolean;
}

export interface GeometryRequest {
  schema_version?: 1;
  prompt?: string | null;
  input_image_id?: string | null;
  output_format?: "glb";
  units?: "meters";
  up_axis?: "Y";
  maximum_triangles?: number;
  maximum_texture_size?: 512 | 1024 | 2048 | 4096;
}

export interface Heartbeat {
  schema_version?: 1;
  node_id: string;
  farm_id: string;
  node_epoch: number;
  controller_generation: number;
  sequence: number;
  observed_plan_revision: number;
  active_attempt_ids?: Array<string>;
  services?: Array<ServiceObservation>;
}

export interface ImageGeneration {
  schema_version?: 1;
  id: string;
  model: string;
  prompt: string;
  negative_prompt?: string;
  shape?: "square" | "landscape" | "portrait";
  steps?: 20 | 30 | 40;
  seed: number;
}

export interface ImagePrompt {
  schema_version?: 1;
  prompt: string;
  negative_prompt?: string;
  shape?: "square" | "landscape" | "portrait";
}

export interface ImagePromptPlan {
  schema_version?: 1;
  action: "generate" | "clarify";
  prompt?: string | null;
  negative_prompt?: string;
  shape?: "square" | "landscape" | "portrait";
  question?: string | null;
  images?: Array<ImagePrompt> | null;
}

export interface ImageProviderInfo {
  schema_version?: 1;
  protocol: "hearth.image.v1";
  model: string;
  model_revision: string;
  manifest_sha256: string;
  shapes: Array<"square" | "landscape" | "portrait">;
  steps: Array<20 | 30 | 40>;
  job_cancellation: boolean;
  offline: boolean;
}

export interface ImageReceipt {
  schema_version?: 1;
  id: string;
  model: string;
  state: "queued" | "running" | "completed" | "cancelled" | "failed" | "interrupted";
  progress: number;
  steps: 20 | 30 | 40;
  seed: number;
  shape: "square" | "landscape" | "portrait";
  width: number;
  height: number;
  reason?: string | null;
  sha256?: string | null;
  execution_released: boolean;
  manifest_sha256: string;
  cancel_requested: boolean;
}

export interface InferenceTarget {
  schema_version?: 1;
  id: string;
  connection_id: string;
  resource_pool_id: string;
  model_id: string;
  state: "configured" | "ready" | "failed" | "disabled";
  features?: Array<string>;
  probed_at?: string | null;
  verified_until?: string | null;
  revision: number;
}

export interface JobScope {
  schema_version?: 1;
  farm_id: string;
  principal_id: string;
  workspace_id: string;
  task_id: string;
  parent_task_id?: string | null;
  authorization_version: number;
  resource_grant_ids?: Array<string>;
  locality?: Locality;
  remaining_budget_id: string;
  audience: string;
  attempt_id: string;
  fencing_token: number;
  expires_at: string;
}

export type Locality = "local_only" | "cloud_allowed";
export interface NodePlan {
  schema_version?: 1;
  farm_id: string;
  node_id: string;
  controller_generation: number;
  node_epoch: number;
  expected_revision: number;
  desired_revision: number;
  services?: Array<ServicePlan>;
  drain_policy?: "finish_active" | "cancel_active";
  expires_at: string;
}

export interface PackageReference {
  schema_version?: 1;
  package_id: string;
  digest: string;
  size_bytes: number;
  signer_id: string;
}

export interface ProviderBootstrap {
  schema_version?: 2;
  id: string;
  path: "local_head" | "joined_member" | "openai" | "existing_service";
  readiness: "unconfigured" | "configured" | "inference_verified" | "admin_agent_ready" | "failed";
  node_id?: string | null;
  deployment_id?: string | null;
  provider_configuration_id?: string | null;
  probe_evidence_id?: string | null;
  reason?: string | null;
  revision: number;
}

export interface ProviderProbeRequest {
  schema_version?: 1;
  expected_revision: number;
  maximum_cost_minor?: number;
  paid_probe_grant_id?: string | null;
}

export interface ProviderResourcePool {
  schema_version?: 1;
  id: string;
  name: string;
  generation_slots?: 1;
  busy: boolean;
  execution_state: "idle" | "running" | "unknown";
}

export interface RecipeDependency {
  schema_version?: 1;
  dependency_id: string;
  package: PackageReference;
  depends_on?: Array<string>;
}

export interface ResourceEnvelope {
  schema_version?: 1;
  ram_bytes: number;
  vram_bytes: number;
  disk_bytes: number;
  cpu_millicores: number;
  generation_slots?: number;
}

export interface RevisionPrecondition {
  schema_version?: 1;
  resource_id: string;
  expected_revision: number;
}

export interface SecureInputReceipt {
  schema_version?: 1;
  receipt_id: string;
  run_id: string;
  resource_id: string;
  form: "provider_credential" | "nas_connector" | "pairing" | "model_license";
  status: "awaiting_input" | "validated" | "failed" | "expired";
  expires_at: string;
}

export interface ServiceObservation {
  schema_version?: 1;
  service_instance_id: string;
  desired_revision: number;
  observed_revision: number;
  state: "unassigned" | "planning" | "downloading" | "installing" | "configuring" | "starting" | "warming" | "ready" | "degraded" | "draining" | "stopped" | "failed";
  reason?: string | null;
  completed_bytes?: number;
  total_bytes?: number | null;
  observed_at: string;
}

export interface ServicePlan {
  schema_version?: 1;
  service_instance_id: string;
  recipe_id: string;
  recipe_digest: string;
  package_digests: Array<string>;
  model_digests?: Array<string>;
  capability_ids?: Array<string>;
  settings?: Record<string, unknown>;
  secret_reference_ids?: Array<string>;
  reservations: ResourceEnvelope;
  pinned?: boolean;
}

export interface ServiceRecipe {
  schema_version?: 1;
  recipe_id: string;
  revision: number;
  digest: string;
  platforms: Array<"windows_amd64" | "linux_amd64" | "darwin_amd64" | "darwin_arm64" | "linux_arm64">;
  capabilities?: Array<string>;
  dependencies: Array<RecipeDependency>;
  entrypoint_id: "llama_cpp" | "diffusers" | "whisper_cpp" | "kokoro_onnx" | "geometry" | "toolbox" | "knowledge" | "storage_gateway";
  minimum_node_protocol?: 1;
  isolation: "native_unprivileged" | "linux_container";
  settings_schema: Record<string, unknown>;
  readiness_probe: string;
  rollback: "compatible" | "restore_required";
}

export interface SpeechGeneration {
  schema_version?: 1;
  id: string;
  model: string;
  voice: string;
  input: string;
}

export interface SpeechProviderInfo {
  schema_version?: 1;
  protocol: "hearth.speech.v1";
  model: string;
  model_revision: string;
  manifest_sha256: string;
  voices: Array<string>;
  default_voice: string;
  maximum_characters?: 6000;
  sample_rate?: 24000;
  job_cancellation: boolean;
  offline: boolean;
}

export interface SpeechReceipt {
  schema_version?: 1;
  id: string;
  model: string;
  voice: string;
  input_sha256: string;
  state: "queued" | "running" | "completed" | "cancelled" | "failed" | "interrupted";
  reason?: string | null;
  sha256?: string | null;
  frames?: number;
  sample_rate?: 24000;
  execution_released: boolean;
  manifest_sha256: string;
  cancel_requested: boolean;
}

export interface TranscriptionProviderInfo {
  schema_version?: 1;
  protocol: "hearth.transcription.v1";
  model: string;
  model_revision: string;
  manifest_sha256: string;
  languages: Array<"en">;
  maximum_seconds?: 120;
  sample_rate?: 16000;
  job_cancellation: boolean;
  offline: boolean;
}

export interface TranscriptionReceipt {
  schema_version?: 1;
  id: string;
  model: string;
  audio_sha256: string;
  state: "queued" | "running" | "completed" | "cancelled" | "failed" | "interrupted";
  reason?: string | null;
  text?: string;
  language?: "en";
  execution_released: boolean;
  manifest_sha256: string;
  cancel_requested: boolean;
}

export interface TranscriptionRequest {
  schema_version?: 1;
  id: string;
  model: string;
  audio_sha256: string;
}

export interface WorkerCommand {
  schema_version?: 1;
  command_id: string;
  node_id: string;
  node_epoch: number;
  operation: "reconcile_plan" | "stage" | "load" | "drain" | "unload" | "cancel_attempt";
  reference_id: string;
  reference_digest: string;
  expires_at: string;
}
