"""Generate JSON schemas, Go/TS wire types and transport endpoint schema from Python contracts."""

import json
from pathlib import Path

from hearth.config import Settings
from hearth.contracts import CONTRACTS
from hearth.main import create_app

ROOT = Path(__file__).resolve().parents[1]


def typescript_type(schema):
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(typescript_type(item) for item in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{typescript_type(schema['items'])}>"
    if kind == "object":
        return "Record<string, unknown>"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(kind, "unknown")


def go_type(schema):
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "anyOf" in schema:
        alternatives = [item for item in schema["anyOf"] if item.get("type") != "null"]
        return "*" + go_type(alternatives[0]) if len(alternatives) == 1 else "any"
    kind = schema.get("type")
    if kind == "array":
        return "[]" + go_type(schema["items"])
    return {"string": "string", "integer": "int64", "number": "float64", "boolean": "bool", "object": "map[string]any"}.get(kind, "any")


def main():
    definitions = {}
    for name, model in sorted(CONTRACTS.items()):
        schema = model.model_json_schema()
        definitions.update(schema.pop("$defs", {}))
        definitions[name] = schema
    bundle = {"$schema": "https://json-schema.org/draft/2020-12/schema", "$id": "https://hearth.invalid/contracts/v1", "$defs": definitions}
    text = json.dumps(bundle, indent=2, sort_keys=True) + "\n"
    for relative in ("packages/contracts/schema/hearth.json", "worker/internal/contracts/schema/hearth.json"):
        path = ROOT / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    ts = ["// Generated by scripts/generate_contracts.py. Do not edit."]
    go = ["// Code generated by scripts/generate_contracts.py. DO NOT EDIT.", "package contracts", ""]
    for name, schema in sorted(definitions.items()):
        if schema.get("type") != "object":
            ts.append(f"export type {name} = {typescript_type(schema)};")
            go.append(f"type {name} {go_type(schema)}")
            continue
        ts.append(f"export interface {name} {{")
        go.append(f"type {name} struct {{")
        for field, definition in schema["properties"].items():
            optional = "" if field in schema.get("required", []) else "?"
            ts.append(f"  {field}{optional}: {typescript_type(definition)};")
            go_name = "".join(part[:1].upper() + part[1:] for part in field.split("_"))
            go.append(f'  {go_name} {go_type(definition)} `json:"{field}"`')
        ts.append("}\n")
        go.append("}\n")
    path = ROOT / "packages/contracts/src/generated.ts"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(ts).rstrip() + "\n", newline="\n")
    (ROOT / "worker/internal/contracts/generated.go").write_text("\n".join(go) + "\n")
    app = create_app(Settings(mode="test"))
    openapi = app.openapi()
    openapi["components"]["schemas"].update(definitions)
    # OpenAPI uses component references, while the JSON Schema bundle uses $defs.
    output = json.dumps(openapi, indent=2, sort_keys=True).replace("#/$defs/", "#/components/schemas/")
    (ROOT / "packages/contracts/openapi.json").write_text(output + "\n")
    print(f"Generated {len(CONTRACTS)} closed wire contracts and {len(definitions)} shared definitions.")


if __name__ == "__main__":
    main()
